kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: image-registry.openshift-image-registry.svc:5000/hello-spring-dev/hello-service:prod-022-06-27-20-11-52
