kind: Deployment
metadata:
  name: hello-service
  namespace: hello-spring-dev
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: image-registry.openshift-image-registry.svc:5000/hello-spring-dev/hello-service:dev-024-01-30-11-45-55
