kind: Deployment
metadata:
  name: hello-service
  namespace: hello-spring-prod
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: quay.io/demo-pipelines/hello-service:prod-2024-01-30-11-49-21
